# Generated by Django 4.2 on 2025-02-18 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('T_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='be_app.teacher')),
            ],
        ),
    ]
