# Generated by Django 5.1.6 on 2025-02-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
