# Generated by Django 5.1.6 on 2025-03-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0005_teacher_password_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classcode',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
