# Generated by Django 5.1.6 on 2025-03-31 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0006_alter_teacher_classcode_alter_teacher_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
