# Generated by Django 5.1.6 on 2025-03-31 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0007_student_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer1", models.CharField(max_length=255)),
                ("answer2", models.CharField(max_length=255)),
                ("answer3", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Must match one of the answer choices", max_length=255
                    ),
                ),
                ("grade", models.IntegerField()),
                (
                    "teacher",
                    models.ForeignKey(
                        db_column="classcode",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="be_app.teacher",
                        to_field="classcode",
                    ),
                ),
            ],
        ),
    ]
