# Generated by Django 5.1.6 on 2025-03-31 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0008_quiz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="T_id",
            new_name="teacher",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer1",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer2",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="answer3",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="question",
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="be_app.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="be_app.question",
                    ),
                ),
            ],
        ),
    ]
