# Generated by Django 5.1.6 on 2025-03-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0009_rename_t_id_student_teacher_remove_quiz_answer1_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="teacher",
            new_name="classcode",
        ),
    ]
