# Generated by Django 5.1.6 on 2025-03-31 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0011_remove_question_quiz_prompt_question_prompt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="classcode",
            new_name="teacher",
        ),
    ]
