# Generated by Django 5.1.6 on 2025-03-31 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0012_rename_classcode_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="be_app.teacher",
                to_field="classcode",
            ),
        ),
    ]
