# Generated by Django 5.1.6 on 2025-03-31 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0013_alter_quiz_teacher"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="teacher",
            new_name="classcode",
        ),
    ]
