# Generated by Django 5.1.6 on 2025-03-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0014_rename_teacher_student_classcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="classcode",
            field=models.CharField(max_length=10),
        ),
    ]
