# Generated by Django 5.1.6 on 2025-04-01 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0015_alter_student_classcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="quiz",
        ),
        migrations.AlterField(
            model_name="question",
            name="prompt",
            field=models.TextField(),
        ),
        migrations.RenameField(
            model_name="question",
            old_name="text",
            new_name="question_text",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_one",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_three",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="option_two",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="be_app.quiz",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Prompt",
        ),
    ]
