# Generated by Django 5.1.6 on 2025-04-01 19:06

import be_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0016_remove_prompt_quiz_alter_question_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                default=be_app.models.get_default_quiz,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="be_app.quiz",
            ),
        ),
    ]
