# Generated by Django 5.1.6 on 2025-04-14 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0018_alter_question_correct_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentScore",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("grade", models.IntegerField()),
                ("score", models.IntegerField()),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="be_app.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="be_app.student",
                    ),
                ),
            ],
        ),
    ]
