# Generated by Django 5.1.6 on 2025-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0019_studentscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentscore",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
