# Generated by Django 5.1.6 on 2025-04-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0020_alter_studentscore_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentscore",
            name="student",
        ),
        migrations.AddField(
            model_name="studentscore",
            name="student_username",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
    ]
