# Generated by Django 5.1.6 on 2025-04-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0021_remove_studentscore_student_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentscore",
            name="classcode",
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
