# Generated by Django 5.1.6 on 2025-04-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0022_studentscore_classcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentscore",
            name="classcode",
            field=models.CharField(max_length=10),
        ),
    ]
