# Generated by Django 5.1.6 on 2025-04-26 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0023_alter_studentscore_classcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="last_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
