# Generated by Django 5.1.6 on 2025-04-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0024_teacher_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="reset_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="reset_token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
