# Generated by Django 5.1.6 on 2025-05-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0025_teacher_reset_token_teacher_reset_token_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="option_one",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_three",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_two",
        ),
        migrations.AddField(
            model_name="question",
            name="option_one_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_one_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_three_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_three_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="question",
            name="option_two_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_two_text",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
