# Generated by Django 5.1.6 on 2025-05-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0026_remove_question_option_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
