# Generated by Django 5.1.6 on 2025-05-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0027_question_question_image_alter_question_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="max_score",
            field=models.IntegerField(default=48),
            preserve_default=False,
        ),
    ]
