# Generated by Django 5.1.6 on 2025-05-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0028_quiz_max_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="type",
            field=models.CharField(default="ELA", max_length=10),
            preserve_default=False,
        ),
    ]
