# Generated by Django 5.1.6 on 2025-05-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("be_app", "0029_quiz_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="type",
            new_name="subject",
        ),
        migrations.AddField(
            model_name="student",
            name="subject",
            field=models.CharField(default="ELA", max_length=10),
            preserve_default=False,
        ),
    ]
